project:
  type: book
  output-dir: docs

book:
  title: "Análise de dados com R"
  author: "Victor G Alcantara"
  date: "30/10/2024"
  chapters:
    - index.qmd
    - class01.qmd
    - class02.qmd
    - class03.qmd
    - class04.qmd
    - class05.qmd
    - references.qmd

bibliography: references.bib
csl: associacao-brasileira-de-normas-tecnicas-numerico.csl
format:
  html:
    theme: cosmo
    css: style.css
  pdf:
    documentclass: scrreprt

editor: visual

